name: plc_inspection
  description: PLC Inspection Helper - Sopralluogo
  version: 1.0.0+1
  environment:
    sdk: '>=2.18.0 <4.0.0'
  dependencies:
    flutter:
    image_picker: ^1.0.0
    path_provider: ^2.1.0
    sqflite: ^2.3.0
    intl: ^0.19.0
    csv: ^6.0.0
    email_validator: ^2.1.0
    permission_handler: ^11.4.0
    share_plus: ^7.0.0
  dev_dependencies:
    flutter_test:
    flutter_lints: ^3.0.0
  flutter:
    uses-material-design: true
